# https://alacritty.org/config-alacritty.html
live_config_reload = true    # 实时配置重新加载

[window]
dimensions = { columns = 74, lines = 24 }  # 窗口尺寸（终端中的行/列数）
padding = { x = 16, y = 26 }               # 窗口周围添加的空白区域
decorations = "transparent"                # 窗口装饰 - 透明(macOS)
dynamic_padding = false                    # 动态填充
dynamic_title = true                       # 动态标题
opacity = 0.82                             # 背景不透明度
option_as_alt = "None"                     # Option(Macos) -> Alt -> OnlyLeft | OnlyRight| Both | None

[scrolling]
history = 2500  # 回滚缓冲区的最大行数
multiplier = 3  # 每个输入滚动增量滚动的行数

[font]
size = 14.6
normal = { family = "Mononoki Nerd Font", style = "Regular" }
bold = { family = "Mononoki Nerd Font", style = "Bold" }
italic = { family = "Mononoki Nerd Font", style = "Italic" }
bold_italic = { family = "Mononoki Nerd Font", style = "Bold Italic" }

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"  # 语义转义字符
save_to_clipboard = true                       # 保存到剪贴板

[cursor]
style = { shape = "Beam", blinking = "Always" }  # 光标样式
unfocused_hollow = false

[mouse]
bindings = [
    { mouse = "Middle", action= "Pasteselection"},
]

[keyboard]
bindings = [
    { key = "V",          mods = "Command",       action = "Paste"},
    { key = "C",          mods = "Command",       action = "Copy"},
    { key = "Q",          mods = "Command",       action = "Quit"},
    { key = "W",          mods = "Command",       action = "Hide"},
    { key = "ArrowUp",    mods = "Command",       action = "ScrollPageUp"},
    { key = "ArrowDown",  mods = "Command",       action = "ScrollPageDown"},
    { key = "T",          mods = "Command",       action = "CreateNewWindow"},        # Command T            -> 创建新窗口
    { key = "Return",     mods = "Command",       action = "ToggleMaximized"},        # Command Return       -> 最大化
    { key = "Return" ,    mods = "Command|Shift", action = "ToggleSimpleFullscreen"}, # Command Shift Return -> 进入全屏而不占用其他空间(Macos)
    { key = "W",          mods = "Command|Shift", action = "HideOtherApplications"},  # Command Shift W      -> 隐藏其他应用程序
    { key = "T",          mods = "Command|Shift", action = "CreateNewTab"},           # Command Shift T      -> 创建新选项卡
    { key = "ArrowLeft",  mods = "Command",       chars = "\u0001"},                  # Command Left         -> Alt-a
    { key = "ArrowRight", mods = "Command",       chars = "\u0005"},                  # Command Right        -> Alt-e
    { key = "Back",       mods = "Command",       chars = "\u0015"},                  # Command Back         -> Alt-U
    { key = "N",          mods = "Command",       chars = "\u0001c"},                 # Command N            -> Alt-a c -> tmux new-window
    { key = "LBracket",   mods = "Command",       chars = "\u0001p"},                 # Command [            -> Alt-a p -> tmux previous-window
    { key = "RBracket",   mods = "Command",       chars = "\u0001n"},                 # Command ]            -> Alt-a n -> tmux next-window
    { key = "X",          mods = "Command",       chars = "\u0001x"},                 # Command X            -> Alt-a x -> tmux kill-pane
    { key = "Key1",       mods = "Command",       chars = "\u00011"},                 # Command 1            -> Alt-a 1 -> tmux select-window -t 1
    { key = "Key2",       mods = "Command",       chars = "\u00012"},
    { key = "Key3",       mods = "Command",       chars = "\u00013"},
    { key = "Key4",       mods = "Command",       chars = "\u00014"},
    { key = "Key5",       mods = "Command",       chars = "\u00015"},
    { key = "Key6",       mods = "Command",       chars = "\u00016"},
    { key = "Key7",       mods = "Command",       chars = "\u00017"},
    { key = "Key8",       mods = "Command",       chars = "\u00018"},
    { key = "Key9",       mods = "Command",       chars = "\u00019"},
]
