# https://yazi-rs.github.io/docs/configuration/yazi
[manager]
show_hidden = false
ratio = [1, 3, 4]

[preview]
tab_size = 2
max_width = 6000  # run yazi --clear-cache
max_height = 6000  # run yazi --clear-cache

