shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.fast-syntax]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
