#format = ""

# 根据 schema 提供自动补全
"$schema" = 'https://starship.rs/config-schema.json'
right_format = """$cmd_duration"""
scan_timeout = 30      # 扫描文件的超时时间
command_timeout = 500  # 执行命令的超时时间
add_newline = false    # 在提示符之间不插入空行

[line_break]
disabled = true

[character]
success_symbol = '[➜](bold bright-yellow)'
error_symbol = '[✗](bold red)'

[cmd_duration]
min_time = 1
format = '[$duration](bold yellow)'

[directory]
truncation_length = 3
truncation_symbol = './'
home_symbol = '~'
read_only = " 󰌾"

[os]
format = '[($symbol)]($style)'
style = "bold blue"
disabled = true

[os.symbols]
Windows = ' '
Macos = ' ' # ' '
# Arch = ' '
# 󰀘 

[package]
disabled = true

[git_branch]
format = 'on [$symbol$branch(:$remote_branch)]($style) '
style = 'bold purple'
# symbol = " "

[c]
format = '[$symbol]($style)'
style = 'bold 149'
symbol = " "
disabled = true

[cmake]
format = '[$symbol]($style)'
style  = 'bold 149'
symbol = " "

[docker_context]
format       = '[$symbol]($style)'
style        = 'blue bold'
symbol       = "  "
detect_files = [ 'docker-compose.yml', 'docker-compose.yaml', 'Dockerfile', 'dockerfile' ]  # 加了个小写的 dockerfile
disabled     = false

[golang]
format = '[$symbol]($style)'
style = 'bold cyan'
symbol = " "
# disabled = true

[lua]
format = '[$symbol]($style)'
style = 'bold blue'
symbol = " "

[nodejs]
format = '[$symbol]($style)'
style = 'bold red'
symbol = " "
# disabled = true

[python]
format = '[$symbol]($style)'
style = 'yello bold'
symbol = " "

[conda]
format = '[$symbol$environment](dimmed green)'
symbol = " "
disabled = true

[rust]
symbol = " "
