ZSH_HOME="$HOME/.config/zsh"

[[ ! -f ${ZSH_HOME}/common.zsh ]] || source ${ZSH_HOME}/common.zsh
[[ ! -f ${ZSH_HOME}/alias.zsh ]] || source ${ZSH_HOME}/alias.zsh
[[ ! -f ${ZSH_HOME}/env.zsh ]] || source ${ZSH_HOME}/env.zsh
[[ ! -f ${ZSH_HOME}/fzf.zsh ]] || source ${ZSH_HOME}/fzf.zsh
[[ ! -f ${ZSH_HOME}/plugins.zsh ]] || source ${ZSH_HOME}/plugins.zsh

#source <(kubectl completion zsh)
